# Generated by Django 2.2.5 on 2020-01-15 15:44

import cores.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191225_0013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cores.managers.CustomUserManager()),
            ],
        ),
    ]
